# Generated by Django 5.0.6 on 2024-06-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Segblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
