# Generated by Django 5.0.6 on 2024-06-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tienda'),
        ),
    ]
